import { fa1, faCarrot, faCircleDollarToSlot, faClock, faComments, faHandshake, faHome, faIceCream, faPaw, faPersonRunning, faTrain, faTreeCity, faQuoteLeft } from '@fortawesome/free-solid-svg-icons'

export const categories = [
    {
        category: "Greetings",
        icon: faHandshake,
    },
    {
        category: "Action Verbs",
        icon: faPersonRunning,
    },
    {
        category: "Phrases",
        icon: faComments,
    },
    {
        category: "Numbers",
        icon: fa1,
    },
    {
        category: "Food",
        icon: faIceCream,
    },
    {
        category: "Buildings",
        icon: faTreeCity,
    },
    {
        category: "Home",
        icon: faHome,
    },
    {
        category: "Transportation",
        icon: faTrain,
    },
    {
        category: "Animals",
        icon: faPaw,
    },
    {
        category: "Time",icon: faClock,
    },
    // {
    //     category: "Time",
    //     icon: "Intermediate",
    // },
    {
        category: "Money",
        icon: faCircleDollarToSlot,
    },
    // {
    //     category: "Money",
    //     icon: "Intermediate",
    // },
]

export const vocab = [
    {
        audio: "apple.wav",
        english: "apple",
        cree: "kāspimin",
        category: "Food",
        englishDisplay: "apple",
        creeDisplay: "kāspimin",
        creeSyllables: ["kās", "pi", "min"],
    },
    {
        audio: "apples.wav",
        english: "apples",
        cree: "kāspimina",
        category: "Food",
        englishDisplay: "apples",
        creeDisplay: "kāspimina",
        creeSyllables: ["kās", "pi", "mina"],
    },
    {
        audio: "orange.wav",  
        english: "orange",
        cree: "osawīmin",
        category: "Food",
        englishDisplay: "orange",
        creeDisplay: "osawīmin",
        creeSyllables: ["osa", "wī", "min"],
    },
    {
        audio: "oranges.wav",  
        english: "oranges",
        cree: "osawīmina",
        category: "Food",
        englishDisplay: "oranges",
        creeDisplay: "osawīmina",
        creeSyllables: ["osa", "wī", "mina"],
    },
    {
        audio: "watermelon.wav",  
        english: "watermelon",
        cree: "nipiwīmin",
        category: "Food",
        englishDisplay: "watermelon",
        creeDisplay: "nipiwīmin",
        creeSyllables: ["ni", "pi", "wī", "min"],
    },
    {
        audio: "watermelons.wav",  
        english: "watermelons",
        cree: "nipiwīmina",
        category: "Food",
        englishDisplay: "watermelons",
        creeDisplay: "nipiwīmina",
        creeSyllables: ["ni", "pi", "wī", "mina"],
    },
    {
        audio: "pear.wav",  
        english: "pear",
        cree: "cipomin",
        category: "Food",
        englishDisplay: "pear",
        creeDisplay: "cipomin",
        creeSyllables: ["ci", "po", "min"],
    },
    {
        audio: "pears.wav",  
        english: "pears",
        cree: "cipomina",
        category: "Food",
        englishDisplay: "pears",
        creeDisplay: "cipomina",
        creeSyllables: ["ci", "po", "mina"],
    },
    {
        audio: "peach.wav",  
        english: "peach",
        cree: "mithawimin",
        category: "Food",
        englishDisplay: "peach",
        creeDisplay: "mithawimin",
        creeSyllables: ["mi", "tha", "wi", "min"],
    },
    {
        audio: "peaches.wav",  
        english: "peaches",
        cree: "mithawimina",
        category: "Food",
        englishDisplay: "peaches",
        creeDisplay: "mithawimina",
        creeSyllables: ["mi", "tha", "wi", "mina"],
    },
    {
        audio: "carrot.wav",  
        english: "carrot",
        cree: "oskātask",
        category: "Food",
        englishDisplay: "carrot",
        creeDisplay: "oskātask",
        creeSyllables: ["os", "kā", "task"],
    },
    {
        audio: "carrots.wav",  
        english: "carrots",
        cree: "oskātaskwa",
        category: "Food",
        englishDisplay: "carrots",
        creeDisplay: "oskātaskwa",
        creeSyllables: ["os", "kā", "task"],
    },
    {
        audio: "onion.wav",  
        english: "onion",
        cree: "wihcīkaskosiy",
        category: "Food",
        englishDisplay: "onion",
        creeDisplay: "wihcīkaskosiy",
        creeSyllables: ["wih", "cī", "kas", "kosiy"],
    },
    {
        audio: "onions.wav",  
        english: "onions",
        cree: "wihcīkaskosiya",
        category: "Food",
        englishDisplay: "onions",
        creeDisplay: "wihcīkaskosiya",
        creeSyllables: ["wih", "cī", "kas", "ko", "siya"],
    },
    {
        audio: "potato.wav",  
        english: "potato",
        cree: "askipwa",
        category: "Food",
        englishDisplay: "potato",
        creeDisplay: "askipwa",
        creeSyllables: ["as", "ki", "pwa"],
    },
    {
        audio: "potatoes.wav",  
        english: "potatoes",
        cree: "askipwawa",
        category: "Food",
        englishDisplay: "potatoes",
        creeDisplay: "askipwawa",
        creeSyllables: ["as", "ki", "pwawa"],
    },
    {
        audio: "bread.wav",  
        english: "bread",
        cree: "ohpihkasikan",
        category: "Food",
        englishDisplay: "bread",
        creeDisplay: "ohpihkasikan",
        creeSyllables: ["oh", "pih", "ka", "sikan"],
    },
    {
        audio: "butter.wav",  
        english: "butter",
        cree: "osawipimiy",
        category: "Food",
        englishDisplay: "butter",
        creeDisplay: "osawipimiy",
        creeSyllables: ["osa", "wi", "pi", "miy"],
    },
    {
        audio: "cheese.wav",  
        english: "cheese",
        cree: "tohtōsāpōhkan",
        category: "Food",
        englishDisplay: "",
        creeDisplay: "tohtōsāpōhkan",
        creeSyllables: ["toh", "tō", "sā", "pōh", "kan"],
    },
    {
        audio: "egg.wav",  
        english: "egg",
        cree: "wawi",
        category: "Food",
        englishDisplay: "egg",
        creeDisplay: "wawi",
        creeSyllables: ["wa", "wi"],
    },
    {
        audio: "ice cream.wav",  
        english: "ice cream",
        cree: "kā tahkāk",
        category: "Food",
        englishDisplay: "ice cream",
        creeDisplay: "kā tahkāk",
        creeSyllables: ["kā", "tah", "kāk"],
    },
    {
        audio: "jello.wav",  
        english: "jello",
        cree: "astōhcikan",
        category: "Food",
        englishDisplay: "jello",
        creeDisplay: "astōhcikan",
        creeSyllables: ["as", "tōh", "ci", "kan"],
    },
    {
        audio: "juice.wav",  
        english: "juice",
        cree: "minisāpoya",
        category: "Food",
        englishDisplay: "juice",
        creeDisplay: "minisāpoya",
        creeSyllables: ["mi", "ni", "sā", "poya"],
    },
    {
        audio: "milk.wav",  
        english: "milk",
        cree: "tohtosāpwiy",
        category: "Food",
        englishDisplay: "milk",
        creeDisplay: "tohtosāpwiy",
        creeSyllables: ["toh", "to", "sā", "pwiy"],
    },
    {
        audio: "pepper.wav",  
        english: "pepper",
        category: "Food",
        cree: "pípaw",
        englishDisplay: "pepper",
        creeDisplay: "pípaw",
        creeSyllables: ["pí", "paw"],
    },
    {
        audio: "rice.wav",  
        english: "rice",
        cree: "wāpihikominak",
        category: "Food",
        englishDisplay: "rice",
        creeDisplay: "wāpihikominak",
        creeSyllables: ["wā", "pihi", "komi", "nak"],
    },
    {
        audio: "salt.wav",  
        english: "salt",
        cree: "siwitakan",
        category: "Food",
        englishDisplay: "salt",
        creeDisplay: "siwitakan",
        creeSyllables: ["si", "wi", "ta", "kan"],
    },
    {
        audio: "soup.wav",  
        english: "soup",
        cree: "mīcimāpōy",
        category: "Food",
        englishDisplay: "soup",
        creeDisplay: "mīcimāpōy",
        creeSyllables: ["mī", "ci", "mā", "pōy"],
    },
    {
        audio: "sugar.wav",  
        english: "sugar",
        cree: "siwinikan",
        category: "Food",
        englishDisplay: "sugar",
        creeDisplay: "siwinikan",
        creeSyllables: ["si", "wi", "ni", "kan"],
    },
    {
        audio: "tea.wav",  
        english: "tea",
        cree: "maskīhkiwapwiy",
        category: "Food",
        englishDisplay: "tea",
        creeDisplay: "maskīhkiwapwiy",
        creeSyllables: ["mas", "kīhki", "wa", "pwiy"],
    },
    {
        audio: "wine.wav",  
        english: "wine",
        cree: "sominapoy",
        category: "Food",
        englishDisplay: "wine",
        creeDisplay: "sominapoy",
        creeSyllables: ["so", "mi", "na", "poy"],
    },
    {
        audio: "morning.wav",  
        english: "morning",
        cree: "kikisipāyāw",
        category: "Time",
        englishDisplay: "morning",
        creeDisplay: "kikisipāyāw",
        creeSyllables: ["kiki", "si", "pā", "yāw"],
    },
    {
        audio: "in the morning.wav",  
        english: "in the morning",
        cree: "kikisipayaki",
        category: "Time",
        englishDisplay: "in the morning",
        creeDisplay: "kikisipayaki",
        creeSyllables: ["kiki", "si", "pa", "yaki"],
    },
    {
        audio: "night.wav",  
        english: "night",
        cree: "tipiskaw",
        category: "Time",
        englishDisplay: "night",
        creeDisplay: "tipiskaw",
        creeSyllables: ["ti", "pis", "kaw"],
    },
    {
        audio: "tonight.wav",  
        english: "tonight",
        cree: "tipisikaki",
        category: "Time",
        englishDisplay: "tonight",
        creeDisplay: "tipisikaki",
        creeSyllables: ["ti", "pi", "si", "kaki"],
    },
    {
        audio: "last evening.wav",  
        english: "last evening",
        cree: "otakosihk",
        category: "Time",
        englishDisplay: "last evening",
        creeDisplay: "otakosihk",
        creeSyllables: ["ota", "ko", "sihk"],
    },
    {
        audio: "last night.wav",  
        english: "last night",
        cree: "tipiskohk",
        category: "Time",
        englishDisplay: "last night",
        creeDisplay: "tipiskohk",
        creeSyllables: ["ti", "pis", "kohk"],
    },
    {
        audio: "later tonight.wav",  
        english: "later tonight",
        cree: "otakosiki",
        category: "Time",
        englishDisplay: "later tonight",
        creeDisplay: "otakosiki",
        creeSyllables: ["ota", "ko", "si", "ki"],
    },
    {
        audio: "tomorrow.wav",  
        english: "tomorrow",
        cree: "wāpahki",
        category: "Time",
        englishDisplay: "tomorrow",
        creeDisplay: "wāpahki",
        creeSyllables: ["wā", "pah", "ki"],
    },
    {
        audio: "tomorrow morning.wav",  
        english: "tomorrow morning",
        cree: "wāpahki kikisípayaki",
        category: "Time",
        englishDisplay: "tomorrow morning",
        creeDisplay: "wāpahki kikisípayaki",
        creeSyllables: ["wā", "pah", "ki", "kiki", "sí", "pa", "yaki"],
    },
    {
        audio: "day after tomorrow.wav",  
        english: "day after tomorrow",
        cree: "awasiwahpahki",
        category: "Time",
        englishDisplay: "day after tomorrow",
        creeDisplay: "awasiwāhpahki",
        creeSyllables: ["awa", "si", "wāh", "pahki"],
    },
    {
        audio: "noon.wav",  
        english: "noon",
        cree: "apihtáwi kisikaw",
        category: "Time",
        englishDisplay: "noon",
        creeDisplay: "apihtáwi kisikaw",
        creeSyllables: ["apih", "táwi", "kisi", "kaw"],
    },
    {
        audio: "at noon.wav",  
        english: "at noon",
        cree: "apihtaaw wikisikaawki",
        category: "Time",
        englishDisplay: "at noon",
        creeDisplay: "apihtaaw wikisikaawki",
        creeSyllables: ["apih", "taaw", "wiki", "si", "kaawki"],
    },
    {
        audio: "midnight.wav",  
        english: "midnight",
        cree: "apihtatipiskaw",
        category: "Time",
        englishDisplay: "midnight",
        creeDisplay: "apihtatipiskaw",
        creeSyllables: ["apih", "tati", "pis", "kaw"],
    },
    {
        audio: "at midnight.wav",  
        english: "at midnight",
        cree: "apihtatipiskaki",
        category: "Time",
        englishDisplay: "at midnight",
        creeDisplay: "apihtatipiskaki",
        creeSyllables: ["apih", "ta", "ti", "pis", "kaki"],
    },
    {
        audio: "past midnight.wav",  
        english: "past midnight",
        cree: "poni apihtatipiskaaw",
        category: "Time",
        englishDisplay: "",
        creeDisplay: "poni apihtatipiskaaw",
        creeSyllables: ["poni", "apih", "tati", "pis", "kaaw"],
    },
    {
        audio: "after midnight.wav",  
        english: "after midnight",
        cree: "poni apihtatipiskaaki",
        category: "Time",
        englishDisplay: "after midnight",
        creeDisplay: "poni apihtatipiskaaki",
        creeSyllables: ["poni", "apih", "tati", "pis", "kaaki"],
    },
    {
        audio: "hello.wav",  
        english: "hello",
        cree: "tānisi",
        category: "Greetings",
        englishDisplay: "hello",
        creeDisplay: "tānisi",
        creeSyllables: ["tāni", "si"],
    },
    {
        audio: "my name is.wav",  
        english: "my name is ___",
        cree: "___ nitisīthihkāson",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [],
    },
    {
        audio: "goodbye.wav",  
        english: "goodbye",
        cree: "īkosi kawapamitin",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "thank you.wav",  
        english: "thank you",
        cree: "īkosani kinanaskomitin",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "you're welcome.wav",  
        english: "you're welcome",
        cree: "īkosi",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "yes1.wav",  
        english: "yes",
        cree: "īhī",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "yes2.wav",  
        english: "yes",
        cree: "tapwī",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "no.wav",  
        english: "no",
        cree: "namwāc",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "sorry.wav",  
        english: "I'm sorry",
        cree: "ni mitatin",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "please.wav",  
        english: "please",
        cree: "please in cree",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "wait.wav",  
        english: "wait",
        cree: "ciskwa",
        category: "Greetings",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "i eat.wav",  
        english: "I eat",
        cree: "I eat in cree",
        category: "Action Verbs",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "i will eat.wav",  
        english: "I will eat",
        cree: "I will eat in cree",
        category: "Action Verbs",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "i ate.wav",  
        english: "I ate",
        cree: "I ate in cree",
        category: "Action Verbs",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "i will go.wav",  
        english: "I will go",
        cree: "I will go in cree",
        category: "Action Verbs",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "i am going.wav",  
        english: "I am going",
        cree: "I am going in cree",
        category: "Action Verbs",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "i went.wav",  
        english: "I went",
        cree: "I went in cree",
        category: "Action Verbs",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "i need.wav",  
        english: "I need",
        cree: "I need in cree",
        category: "Action Verbs",
        englishDisplay: "",
        creeDisplay: "",
        creeSyllables: [""],
    },
    {
        audio: "bird.wav",  
        english: "bird",
        cree: "pithisis",
        category: "Animals",
        englishDisplay: "bird",
        creeDisplay: "pithisis",
        creeSyllables: ["pi", "thi" , "sis"],
    },
    {
        audio: "dog.wav",  
        english: "dog",
        cree: "atim",
        category: "Animals",
        englishDisplay: "dog",
        creeDisplay: "atim",
        creeSyllables: ["a", "tim"],
    },
    {
        audio: "cat.wav",  
        english: "cat",
        cree: "posis",
        category: "Animals",
        englishDisplay: "cat",
        creeDisplay: "posis",
        creeSyllables: ["po", "sis"],
    },
    {
        audio: "horse.wav",  
        english: "horse",
        cree: "mistatim",
        category: "Animals",
        englishDisplay: "horse",
        creeDisplay: "mistatim",
        creeSyllables: ["mi", "sta", "tim"],
    },
    {
        audio: "bear.wav",  
        english: "bear",
        cree: "māskwa",
        category: "Animals",
        englishDisplay: "bear",
        creeDisplay: "māskwa",
        creeSyllables: ["mās", "kwa"],
    },
    {
        audio: "moose.wav",  
        english: "moose",
        cree: "moswak",
        category: "Animals",
        englishDisplay: "moose",
        creeDisplay: "moswak",
        creeSyllables: ["mo", "swak"],
    },
    {
        audio: "buffalo.wav",  
        english: "buffalo",
        cree: "paskwawi mostos",
        category: "Animals",
        englishDisplay: "buffalo",
        creeDisplay: "paskwawi mostos",
        creeSyllables: ["pas", "kwa", "wi", "mos", "tos"],
    },
    {
        audio: "rabbit.wav",  
        english: "rabbit",
        cree: "wāpos",
        category: "Animals",
        englishDisplay: "rabbit",
        creeDisplay: "wāpos",
        creeSyllables: ["wā", "pos"],
    },
    {
        audio: "washroom.wav",  
        english: "washroom",
        cree: "pamihīsowīkamik",
        category: "Home",
        englishDisplay: "washroom",
        creeDisplay: "pamihīsowīkamik",
        creeSyllables: ["pami", "hīso", "wī", "ka", "mik"],
    },
    {
        audio: "door.wav",  
        english: "door",
        cree: "iskwāhtim",
        category: "Home",
        englishDisplay: "door",
        creeDisplay: "iskwāhtim",
        creeSyllables: ["is", "kwāh", "tim"],
    },
    {
        audio: "window.wav",  
        english: "window",
        cree: "wāsīnamāwin",
        category: "Home",
        englishDisplay: "window",
        creeDisplay: "wāsīnamāwin",
        creeSyllables: ["wā", "sīna", "mā", "win"],
    },
    {
        audio: "kitchen.wav",  
        english: "kitchen",
        cree: "piminawasowikamik",
        category: "Home",
        englishDisplay: "kitchen",
        creeDisplay: "piminawasowikamik",
        creeSyllables: ["pimi", "nawa", "sowi", "ka", "mik"],
    },
]

export const sentenceCategories = [
    {
        category: "Build Sentences",
        icon: faQuoteLeft,
    },
    {
        category: "Conversation",
        icon: faPersonRunning,
    },
]

export const playAudio = (item) => {
    let audio = new Audio(`/assets/sounds/${item.category}/${item.audio}`)
    var resp = audio.play()
    if (resp!== undefined) {
        resp.then(_ => {
            // autoplay starts!
        }).catch(error => {
           //show error
        });
    }
    // console.log(`/assets/sounds/${item.category}/${item.audio}`, audio);
}

export function shuffleArray(array){
    let shuffled = array
        .map(value => ({ value, sort: Math.random() }))
        .sort((a, b) => a.sort - b.sort)
        .map(({ value }) => value)
    // console.log(shuffled);
    return shuffled;
}
